### ISSUE TITLE
Add Non-SPDX License Exception

### ISSUE THREAD

**Issue by zicklag** [EmbarkStudios/cargo-deny#349] opened 2021-06-09 21:11 UTC
**Is your feature request related to a problem? Please describe.**
My organization's crates use a custom license that hasn't been added to the SPDX license list yet and there is no way currently for me to tell cargo deny to allow my custom license in dependencies.

**Describe the solution you'd like**
Would it be possible to add exceptions for certain licenses by giving them either an identifier or a file hash or contents without requiring them to be in the SPDX list?

**Describe alternatives you've considered**
Maybe the best solution, and probably what we will end up doing, would be to add our license to the SPDX list. Still, they only release updates to the SPDX list every quarter so even if we added our license to the list it would be nice to have an interim solution in cargo deny that would work immediately.

**Additional context**
Nothing that I can think of at the moment.

**Comment by Jake-Shadle** [comment] 2021-06-10 08:02
Custom license identifiers are [supported](https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html#spdx-identifiers), simply prefix your license with `LicenseRef-`, this is supported in either a license clarification or the cargo manifest `license` field.

Duplicate of #325

**Closed by Jake-Shadle** 2021-06-10 08:02 UTC
Labels: enhancement

**Comment by zicklag** [comment] 2021-06-11 16:17
Oh, cool, sorry I missed it in the docs! Thanks!
